Title: Global Settings

icon: settings
label: Global Settings
columns:
  left:
    width: 1/2
    fields:
      logo:
        label: Logo
        type: files
        layout: cards
        width: 1/2
      mainEmail:
        label: Primary Email
        type: email
        help: This is the email shown in footer.
      twitterLink:
        icon: twitter-x-fill
        label: Twitter Account
        type: url
        width: 1/2
      linkedinLink:
        icon: linkedin-fill
        label: LinkedIn Account
        type: url
        width: 1/2
      addresses:
        label: Addresses
        type: structure
        fields:
          streetAddress:
            label: Street Address
            type: textarea
            buttons: false
            size: small
          country:
            label: Country
            type: text
          city:
            label: City
            type: text
          postcode:
            label: Eircode / Postcode
            type: text
          image:
            label: Image
            type: files
            max: 1
          mapLocation:
            label: Google Maps link
            type: url
      logos:
        label: Logo Strip Logos
        type: files
        width: 1/1
        layout: cardlets
        size: small


  right:
    width: 1/2
    fields:
      googleAnalytics:
        label: Google Analytics
        type: text
      headerInjection:
        label: Header Injection
        type: textarea
        size: medium
        buttons: false
      footerInjection:
        label: Footer Injection
        type: textarea
        size: medium
        buttons: false
